# Generated by Django 4.1.7 on 2023-04-18 21:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_collectorunit_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waste_type', models.CharField(choices=[('general', 'general'), ('organic', 'organic'), ('hazardous', 'hazardous')], max_length=128)),
                ('waste_desc', models.TextField(blank=True, null=True)),
                ('waste_quantity', models.IntegerField()),
                ('collection_datetime', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('pick_up_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wcrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
