# Generated by Django 4.1.7 on 2023-04-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_collectorunit_user_collector_unit'),
        ('waste', '0002_collectorunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectorUnit',
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='collector_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcrs', to='user.collectorunit'),
        ),
        migrations.AlterField(
            model_name='wastecollectionrequest',
            name='pick_up_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wcrs', to='user.location'),
        ),
    ]
