# Generated by Django 4.1.7 on 2023-04-20 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste', '0005_payment_alter_wastecollectionrequest_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastecollectionrequest',
            old_name='user',
            new_name='requester',
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wcrs_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
