# Generated by Django 4.1.7 on 2023-04-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0006_rename_user_wastecollectionrequest_requester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecollectionrequest',
            name='collector_unit',
        ),
    ]
