# Generated by Django 4.1.7 on 2023-04-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_collectorunit_user_user_type_user_collector_unit'),
        ('waste', '0007_remove_wastecollectionrequest_collector_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='collector_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wcrs', to='user.collectorunit'),
        ),
    ]
