# Generated by Django 4.1.7 on 2023-04-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0008_wastecollectionrequest_collector_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecollectionrequest',
            name='admin',
        ),
    ]
