# Generated by Django 4.1.7 on 2023-04-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("waste", "0009_remove_wastecollectionrequest_admin"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='wastecollectionrequest',
        #     name='payment',
        # ),
        migrations.AddField(
            model_name="payment",
            name="wcr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="waste.wastecollectionrequest",
            ),
        ),
    ]
