# Generated by Django 4.1.7 on 2023-05-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0013_wastecollectionrequest_is_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecollectionrequest',
            name='is_collected',
        ),
    ]
