# Generated by Django 4.1.7 on 2023-05-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0014_remove_wastecollectionrequest_is_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecollectionrequest',
            name='waste_type',
            field=models.CharField(choices=[('General', 'General'), ('Organic', 'Organic'), ('Hazardous', 'Hazardous')], max_length=128),
        ),
    ]
