# Generated by Django 4.1.7 on 2023-06-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0016_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='wcr_id',
            field=models.CharField(default=12345678, editable=False, max_length=128),
            preserve_default=False,
        ),
    ]
