# Generated by Django 4.1.7 on 2023-06-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0017_wastecollectionrequest_wcr_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastecollectionrequest',
            old_name='wcr_id',
            new_name='public_id',
        ),
    ]
