# Generated by Django 4.2.2 on 2023-06-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_remove_location_picture'),
        ('waste', '0019_rename_requester_wastecollectionrequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
        migrations.AddField(
            model_name='payment',
            name='account_no',
            field=models.CharField(default=12354953629656, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_on_payments', to='user.paymentmethod'),
        ),
    ]
