# Generated by Django 4.2.2 on 2023-06-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0021_wastecollectionrequest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecollectionrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=7.43, max_digits=15),
            preserve_default=False,
        ),
    ]
