# Generated by Django 4.2.2 on 2023-06-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0022_alter_wastecollectionrequest_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='account_no',
        ),
    ]
