# Generated by Django 4.2.2 on 2023-06-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0025_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=4.12, max_digits=15),
            preserve_default=False,
        ),
    ]
