# Generated by Django 4.1.7 on 2023-04-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_collectorunit_alter_user_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectorUnit',
        ),
    ]
