# Generated by Django 4.1.7 on 2023-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.CharField(default='sample', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.CharField(default='sample', max_length=255),
            preserve_default=False,
        ),
    ]
