# Generated by Django 4.1.7 on 2023-04-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0007_remove_wastecollectionrequest_collector_unit'),
        ('user', '0010_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collector_unit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='CollectorUnit',
        ),
    ]
