# Generated by Django 4.1.7 on 2023-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_collectorunit_country_collectorunit_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorunit',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
