# Generated by Django 4.1.7 on 2023-04-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_collectorunit_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='momo_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
