# Generated by Django 4.1.7 on 2023-04-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorunit',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collectorunit',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
