# Generated by Django 4.1.7 on 2023-04-29 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_collectorunit_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector_units_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
