# Generated by Django 4.1.7 on 2023-04-29 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_is_suspended_user_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectorunit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='collectorunit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector_units_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectorunit',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
