# Generated by Django 4.1.7 on 2023-04-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_collectorunit_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorunit',
            name='name',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
