# Generated by Django 4.1.7 on 2023-04-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_collectorunit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorunit',
            name='country',
            field=models.CharField(default='gh', max_length=24),
        ),
        migrations.AlterField(
            model_name='collectorunit',
            name='region',
            field=models.CharField(default='ga', max_length=24),
        ),
    ]
