# Generated by Django 4.1.7 on 2023-04-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_user_collector_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collector_id',
        ),
    ]
