# Generated by Django 4.1.7 on 2023-05-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
