# Generated by Django 4.1.7 on 2023-06-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_user_collector_id_alter_collectorunit_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Ghana', max_length=56),
        ),
    ]
