# Generated by Django 4.1.7 on 2023-06-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='picture',
        ),
    ]
