# Generated by Django 4.2.2 on 2023-06-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_rename_address_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name_on_card',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='security_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
