# Generated by Django 4.2.2 on 2023-06-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_paymentmethod_expiry_date_paymentmethod_name_on_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='number',
            new_name='account_number',
        ),
    ]
