# Generated by Django 4.2.2 on 2023-06-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_rename_number_paymentmethod_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='forgot_password_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
