# Generated by Django 4.2.2 on 2023-06-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_user_forgot_password_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='forgot_password_code_expires',
            new_name='forgot_password_code_expires_at',
        ),
    ]
